import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const nourd = Rubik({
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "500", "700", "900"],
});
// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
      <div className="w-full flex-none md:w-64"></div>
      <div className="flex-grow p-6 md:overflow-y-auto md:p-12">{children}</div>
    </div>
  );
}
